name: Generate terraform docs
# Scopo: generazione documentazione
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject

    - name: Upload rendered README artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-docs-readme
        path: README.md
